---
title: "Assignment 1"
author: "Andreas Lydakis - al1076"
output:
  html_document: default
  pdf_document: default
header-includes: \usepackage{bbm}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment 1 #

**Due**: 8/30

## Problem 1 ##

Consider the following problem. You are selling *strawberries* and every day you need to purchase a certain quantity from a distributor. Your cost to buy a pint is $`c`$ and the price you sell it for is $`p`$. That means that with every sale you make $`p-c`$. You have to make the purchase decision in the morning before knowing the demand, which is distributed according to a random variable with CDF $`F`$. 

Strawberries spoil quickly and they must be discarded at the end of the day, leading to a loss of value $p$ for each pint. 

Check out the [simple simulator](https://rlrl.shinyapps.io/fruitvendor/) from the class too. (Look for the source code in the folder Code in this repository)
 
The optimal quantity $`q`$ to order in the morning is (see e.g. [Wikipedia](https://en.wikipedia.org/wiki/Newsvendor_model)):
\[
q = F^{-1}\left( \frac{p - c}{p} \right)~.
\]
Prove it.
*Hint*: Using [Leibniz integral rule](https://en.wikipedia.org/wiki/Leibniz_integral_rule), one can show that:
\[
\mathbb{E}[\min\{ X - q, 0 \}] = -F(q)\\
\]


For every pint under the demand the vendor loses $l_1 = p-c$ credits. For a given demand $\hat{d}$ the amount of units under the demand $a_1$ is equal $0$ if $q \geq \hat{d}$ or is equal to $\hat{d}-q$ if $q\leq \hat{d}$. This means that $a_1=max\{\hat{d}-q, 0\}$

For every pint that is over the demand the vendor loses $l_2 = c$ credits. For a given demand $d$ the amount of units under the demand $a_2$ is equal to $0$ if $\hat{d} \leq q$ or $\hat{d}-q$ if $\hat{d}\geq q$. This means that $a_2=max\{\hat{d}-d, 0\}$

The total expected cost when quantity $q$ is purchased can be written as:

$C(q) = l_1\mathbb{E}(a_1) + l_2\mathbb{E}(a_2) = l_1\mathbb{E}(max\{\hat{d}-q, 0\}) + l_2\mathbb{E}(max\{q-\hat{d}, 0\})$

An expexted value can be expressed as an integral $\mathbb{E}(X) = \int_{\Omega}(X)d\mathbb{P}$ where $\Omega$ is the probability space and $\mathbb{P}$ is the probability measure. So:

$C(q) = l_1\int max\{\hat{d}-q, 0\}f(\hat{d})d\hat{d} + l_2\int max\{q-\hat{d}, 0\}f(\hat{d})d\hat{d}$ where $f(\hat{d})=\frac{d}{d\hat{d}}F(\hat{d})$ In our case $F(d)$ is the probability of the demand being $\leq d$

$C(q) = l_1\int_{q}^{\infty}(\hat{d}-q)f(\hat{d})d\hat{d} + l_2\int_{0}^{\hat{d}} (q-\hat{d})f(\hat{d})d\hat{d}$

From Leibniz's rule, since the limits are constants:

<!-- $\frac{d}{dq}C(q) = l_1\int_{q}^{\infty}f(\hat{d})d\hat{d} + l_2\int_{0}^{\hat{d}}f(\hat{d})d\hat{d} \rightarrow$ -->


$\frac{d}{dq}C(q) = l_2\int_{0}^{q}f(\hat{d})d\hat{d} - l_1\int_{q}^{\infty}f(\hat{d})d\hat{d} = l_2F(q) - l_1(1-F(q))$

We want $l_2F(q) - l_1(1-F(q)) = 0 \rightarrow l2F(q) - l1 - l1F(q) = 0\rightarrow F(q)(l2 + l1) - l1 = 0 \rightarrow F(q) = \frac{l1}{l2+l1} = \frac{p-c}{p}$

## Problem 2 ##

Now you are selling candy instead. Candy does not spoil and any unsold quantity can be stored and sold the following day. Storing unsold quantity incurrs a holding cost. Does this affect the optimality of the solution above? Formulate the problem as an MDP. Describes states, actions, rewards, probabilities, horizon, discount, and anything else that you think is relevant. Also see Example 1 on Page 9 of ARL.

States $S = {S_1, ..., S_n}$ where $S_i$ is the state of having $i$ items in the inventor.

Action set $A = {A_1, ..., A_n}$ where $A_i$ is the action to buy $i$ items.

Each item is bought at price $c$ and sold at price $p$, and are kept in inventory with holding cost $h$. Current items at inventory at time $t$ are denoted $I_t$

Reward at $t+1$ $R_{t+1} = -A_tc - S_th + min(A_t + S_t, n) + $ 